name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Build marketing site
      - name: Build marketing site
        run: |
          cd apps/marketing
          npm ci
          npm run build
      
      # Deploy marketing site
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THE_LAUNDRY_HIVE }}
          channelId: live
          projectId: the-laundry-hive
          target: marketing
```